<robot name="Rose20" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="../common.xacro" />
  <xacro:include filename="../wheel_unit_60mm/wheel_unit_60mm_macro.xacro" />

  

  <xacro:property name="base_size_x" value="0.76" />
  <xacro:property name="base_size_y" value="0.58" />
  <xacro:property name="base_size_z" value="0.05" />
  <xacro:property name="base_pose_x" value="0.0" />
  <xacro:property name="base_pose_y" value="0.0" />
  <xacro:property name="base_pose_z" value="0.2" />

  <xacro:property name="wheel_front_x"    value="0.28" />
  <xacro:property name="wheel_back_x"     value="-0.305" />
  <xacro:property name="wheelbase_width"  value="0.23" />

  <gazebo>
    <static>false</static>
  </gazebo>

  <link name='base'>
    <xacro:default_box  xyz=  "${base_pose_x} ${base_pose_y} ${base_pose_z}" 
                        rpy=  "0 0 0" 
                        size= "${base_size_x} ${base_size_y} ${base_size_z}"/>  
    <xacro:default_inertial mass="30.0"/>
  </link>  
  
  <xacro:wheel_unit_60mm name="wheel_FL" parent="base" xyz="${wheel_front_x} ${-wheelbase_width} ${base_pose_z - base_size_z/2}" rpy="0 0 ${-pi/2}"/>
  <xacro:wheel_unit_60mm name="wheel_FR" parent="base" xyz="${wheel_front_x} ${wheelbase_width}  ${base_pose_z - base_size_z/2}" rpy="0 0 ${pi/2}"/>
  <xacro:wheel_unit_60mm name="wheel_BL" parent="base" xyz="${wheel_back_x}  ${-wheelbase_width} ${base_pose_z - base_size_z/2}" rpy="0 0 ${-pi/2}"/>
  <xacro:wheel_unit_60mm name="wheel_BR" parent="base" xyz="${wheel_back_x}  ${wheelbase_width}  ${base_pose_z - base_size_z/2}" rpy="0 0 ${pi/2}"/>

 
</robot>
