<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

 <include filename="$(find cyton_gamma)/new/urdf/properties/properties.urdf.xacro" />

 <xacro:macro name="joint_arm" params="suffix radius length parent type_box type_cyl *size *limit_box *limit_cyl *origin_box *origin_cyl">
  <!--Part 1: box -->
  <joint name="arm_joint_box_${suffix}" type="${type_box}" >
    <parent link="${parent}" />
    <child link="arm_link_box_${suffix}" />
     <insert_block name="limit_box"/>
    <axis xyz="0 0 1"/>
     <insert_block name="origin_box"/>
  </joint>
  <link name="arm_link_box_${suffix}">
    <visual>
      <material name="color_black">
        <color rgba="0 0 0 1"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
         <insert_block name="size"/>
      </geometry>
    </visual>
  </link>
  <!--Part 2: cylinder -->
 <joint name="arm_joint_cyl_${suffix}" type="${type_cyl}" >
    <parent link="arm_link_box_${suffix}" />
    <child link="arm_link_cyl_${suffix}" />
     <insert_block name="limit_cyl"/>
    <axis xyz="0 0 1"/>
    <insert_block name="origin_cyl"/>
  </joint>
  <link name="arm_link_cyl_${suffix}">
    <visual>
      <material name="grey">
        <color rgba=".2 .2 .2 1"/>
      </material>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${radius}" length="${length}" />
      </geometry>
    </visual>
  </link>
 </xacro:macro>

  <!-- cyton_gamma_arm: joint1 t/m joint5 -->
 <xacro:macro name="cyton_gamma_arm">
   <xacro:joint_arm  
                  suffix=    "1"
                  radius=    "${j1_radius}"
                  length=    "${j1_length}"
                  parent=    "base_link_2" 
                  type_box=  "revolute"
                  type_cyl=  "revolute">
                  <box size ="${j1_l} ${j1_b} ${j1_h}" />
                  <limit lower="-${M_PI}" upper="${M_PI}" effort="1000" velocity="1000"/>
                  <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="1000" velocity="1000"/>
                  <origin xyz="0 0 ${(base_length_2/2) + (j1_h /2)}" rpy="0 0 0"/>
                  <origin xyz="0 0 ${(j1_h/2) + j1_radius}" rpy="${M_PI/2} 0 0"/>
  </xacro:joint_arm>
  
  <xacro:joint_arm 
                  suffix=    "2"
                  radius=    "${j2_radius}"
                  length=    "${j2_length}"
                  parent=    "arm_link_cyl_1" 
                  type_box=  "fixed"
                  type_cyl=  "revolute">
                  <box size ="${j2_l} ${j2_b} ${j2_h}" />
                  <limit lower="0" upper="0" effort="0" velocity="0"/>
                  <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="1000" velocity="1000"/>
                  <origin xyz="0 ${j1_radius + (j2_h /2)} 0" rpy="-${M_PI/2} 0 0"/>
                  <origin xyz="0 0 ${(j2_h/2) + j2_radius}" rpy="0 ${M_PI/2} 0"/>
  </xacro:joint_arm>
  
  <xacro:joint_arm 
                  suffix=    "3"
                  radius=    "${j3_radius}"
                  length=    "${j3_length}"
                  parent=    "arm_link_cyl_2" 
                  type_box=  "fixed"
                  type_cyl=  "revolute">
                  <box size ="${j3_l} ${j3_b} ${j3_h}" />
                  <limit lower="0" upper="0" effort="0" velocity="0"/>
                  <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="1000" velocity="1000"/>
                  <origin xyz="-${j2_radius + (j3_h /2)} 0 0" rpy="0 -${M_PI/2} 0"/>
                  <origin xyz="0 0 ${(j3_h/2) + j3_radius}" rpy="${M_PI/2} 0 0"/>
  </xacro:joint_arm>
  
  <xacro:joint_arm 
                  suffix=    "4"
                  radius=    "${j4_radius}"
                  length=    "${j4_length}"
                  parent=    "arm_link_cyl_3" 
                  type_box=  "fixed"
                  type_cyl=  "revolute">
                  <box size ="${j4_l} ${j4_b} ${j4_h}" />
                  <limit lower="0" upper="0" effort="0" velocity="0"/>
                  <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="1000" velocity="1000"/>
                  <origin xyz="0 ${j3_radius + (j4_h /2)} 0" rpy="-${M_PI/2} 0 0"/>
                  <origin xyz="0 0 ${(j4_h/2) + j4_radius}" rpy="0 ${M_PI/2} 0"/>
  </xacro:joint_arm>
  
  <xacro:joint_arm 
                  suffix=    "5"
                  radius=    "${j5_radius}"
                  length=    "${j5_length}"
                  parent=    "arm_link_cyl_4" 
                  type_box=  "fixed"
                  type_cyl=  "revolute">
                  <box size ="${j5_l} ${j5_b} ${j5_h}" />
                  <limit lower="0" upper="0" effort="0" velocity="0"/>
                  <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="1000" velocity="1000"/>
                  <origin xyz="-${j4_radius + (j5_h /2)} 0 0" rpy="0 -${M_PI/2} 0"/>
                  <origin xyz="0 0 ${(j5_h/2) + j5_radius}" rpy="${M_PI/2} 0 0"/>
  </xacro:joint_arm>

 </xacro:macro>
  
</robot>
