<robot name="cyton_gamma_1500" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:property name="link1_x" value="0.1" />
	<xacro:property name="link1_y" value="0.1" />
	<xacro:property name="link1_z" value="0.5" />

	<xacro:property name="link2_x" value="0.05" />
	<xacro:property name="link2_y" value="0.05" />
	<xacro:property name="link2_z" value="0.5" />

	<xacro:property name="link3_x" value="0.025" />
	<xacro:property name="link3_y" value="0.025" />
	<xacro:property name="link3_z" value="0.5" />

	<xacro:property name="link4_x" value="0.05" />
	<xacro:property name="link4_y" value="0.05" />
	<xacro:property name="link4_z" value="0.5" />

	<xacro:property name="link5_x" value="0.025" />
	<xacro:property name="link5_y" value="0.025" />
	<xacro:property name="link5_z" value="0.5" />

	<xacro:property name="link6_x" value="0.05" />
	<xacro:property name="link6_y" value="0.05" />
	<xacro:property name="link6_z" value="0.5" />

	<xacro:property name="link7_x" value="0.025" />
	<xacro:property name="link7_y" value="0.025" />
	<xacro:property name="link7_z" value="0.5" />

	<xacro:property name="link8_x" value="0.05" />
	<xacro:property name="link8_y" value="0.05" />
	<xacro:property name="link8_z" value="0.5" />

	<!-- Used for fixing robot to Gazebo 'base_link' -->
	<link name="world"/>

	<joint name="fixed" type="fixed">
		<parent link="world"/>
		<child link="link1"/>
	</joint>
	
	<link name="link1">	
		<collision>
	      <origin xyz="0 0 ${link1_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link1_x} ${link1_y} ${link1_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link1_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link1_z/2}" rpy="0 0 0" />
			<geometry>
				<box size="${link1_x} ${link1_y} ${link1_z}"/>
			</geometry>
		</visual>		
	</link>

	<link name="link2">
		<collision>
	      <origin xyz="0 0 ${link2_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link2_x} ${link2_y} ${link2_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link2_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link2_z/2}" rpy="0 0 0" />
			<geometry>
				<box size="${link2_x} ${link2_y} ${link2_z}"/>
			</geometry>
		</visual>
	</link>

	<link name="link3">
		<collision>
	      <origin xyz="0 0 ${link3_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link3_x} ${link3_y} ${link3_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link3_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link3_z/2}" rpy="0 0 0" />
			<geometry>
				<box size="${link3_x} ${link3_y} ${link3_z}"/>
			</geometry>
		</visual>
	</link>

	<link name="link4">
		<collision>
	      <origin xyz="0 0 ${link4_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link4_x} ${link4_y} ${link4_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link4_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link4_z/2}" rpy="0 0 0" />
			<geometry>				
				<box size="${link4_x} ${link4_y} ${link4_z}"/>
			</geometry>
		</visual>
	</link>

	<link name="link5">
		<collision>
	      <origin xyz="0 0 ${link5_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link5_x} ${link5_y} ${link5_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link5_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link5_z/2}" rpy="0 0 0" />
			<geometry>				
				<box size="${link5_x} ${link5_y} ${link5_z}"/>
			</geometry>
		</visual>
	</link>

	<link name="link6">
		<collision>
	      <origin xyz="0 0 ${link6_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link6_x} ${link6_y} ${link6_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link6_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link6_z/2}" rpy="0 0 0" />
			<geometry>				
				<box size="${link6_x} ${link6_y} ${link6_z}"/>
			</geometry>
		</visual>
	</link>

	<link name="link7">
		<collision>
	      <origin xyz="0 0 ${link7_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link7_x} ${link7_y} ${link7_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link7_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link7_z/2}" rpy="0 0 0" />
			<geometry>				
				<box size="${link7_x} ${link7_y} ${link7_z}"/>
			</geometry>
		</visual>
	</link>
	<link name="link8">
		<collision>
	      <origin xyz="0 0 ${link8_z/2}" rpy="0 0 0"/>
	      <geometry>
	    	<box size="${link8_x} ${link8_y} ${link8_z}"/>
	      </geometry>
	    </collision>

	    <inertial>
	      <origin xyz="0 0 ${link8_z/2}" rpy="0 0 0"/>
	      <mass value="1"/>
	      <inertia 
		    ixx="1.0" ixy="0.0" ixz="0.0" 
		    iyy="1.0" iyz="0.0" 
		    izz="1.0"/>
	    </inertial>

		<visual>
			<origin xyz="0 0 ${link8_z/2}" rpy="0 0 0" />
			<geometry>				
				<box size="${link8_x} ${link8_y} ${link8_z}"/>
			</geometry>
		</visual>
	</link>





	<joint name="joint1" type="revolute">
      <parent link="link1"/>
      <child link="link2"/>
      <origin xyz="0 0 0.5" rpy="0 0 0" />
      <axis xyz="0.0 0.0 1.0" /> 
      <limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
    </joint>

	<joint name="joint2" type="revolute">
		<parent link="link2"/>
		<child link="link3"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="1.0 0.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>

	<joint name="joint3" type="revolute">
		<parent link="link3"/>
		<child link="link4"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="0.0 1.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>

	<joint name="joint4" type="revolute">
		<parent link="link4"/>
		<child link="link5"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="1.0 0.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>

	<joint name="joint5" type="revolute">
		<parent link="link5"/>
		<child link="link6"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="0.0 1.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>

	<joint name="joint6" type="revolute">
		<parent link="link6"/>
		<child link="link7"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="0.0 1.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>

	<joint name="joint7" type="revolute">
		<parent link="link7"/>
		<child link="link8"/>
		<origin xyz="0 0 0.5" rpy="0 0 0" />
		<axis xyz="0.0 1.0 0.0" /> 
		<limit effort="1000.0" lower="-0.78535" upper="0.78535" velocity="0.5"/>
	</joint>



</robot>