<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- parameters -->
  <xacro:property name="wheel_base_size_x" value="0.12" />
  <xacro:property name="wheel_base_size_y" value="0.09" />
  <xacro:property name="wheel_base_size_z" value="0.04" />
  <xacro:property name="wheel_base_pose_x" value="0.0" />
  <xacro:property name="wheel_base_pose_y" value="0.0" />
  <xacro:property name="wheel_base_pose_z" value="0.190" />
  <xacro:property name="wheel_base_angle" value="2.356" />

  <xacro:property name="wheel_mount_axle_radius" value="0.0125" />
  <xacro:property name="wheel_mount_axle_length" value="0.02" />
  <xacro:property name="wheel_mount_axle_pose_x" value="0.04" />
  <xacro:property name="wheel_mount_axle_pose_y" value="0.0" />
  <xacro:property name="wheel_mount_axle_pose_z" value="0.180" />

  <xacro:property name="wheel_horplate_size_x" value="0.14" />
  <xacro:property name="wheel_horplate_size_y" value="0.04" />
  <xacro:property name="wheel_horplate_size_z" value="0.005" />
  <xacro:property name="wheel_horplate_pose_x" value="-0.01" />
  <xacro:property name="wheel_horplate_pose_y" value="0.0" />
  <xacro:property name="wheel_horplate_pose_z" value="0.16" />

  <xacro:property name="wheel_vertplate_size_x" value="0.005" />
  <xacro:property name="wheel_vertplate_size_y" value="0.04" />
  <xacro:property name="wheel_vertplate_size_z" value="0.12" />
  <xacro:property name="wheel_vertplate_pose_x" value="-0.08" />
  <xacro:property name="wheel_vertplate_pose_y" value="0.0" />
  <xacro:property name="wheel_vertplate_pose_z" value="0.10" />

  <xacro:property name="wheel_axle_radius" value="0.015" />
  <xacro:property name="wheel_axle_length" value="0.10" />
  <xacro:property name="wheel_axle_pose_x" value="-0.03" />
  <xacro:property name="wheel_axle_pose_y" value="0.0" />
  <xacro:property name="wheel_axle_pose_z" value="0.06" />
  <xacro:property name="wheel_axle_pose_r" value="0.0" />
  <xacro:property name="wheel_axle_pose_p" value="1.5707" />
  <xacro:property name="wheel_axle_pose_y" value="0.0" />

  <xacro:property name="wheel_radius" value="0.06" />
  <xacro:property name="wheel_length" value="0.03" />
  <xacro:property name="wheel_pose_x" value="0.03" />
  <xacro:property name="wheel_pose_y" value="0.0" />
  <xacro:property name="wheel_pose_z" value="0.06" />
  <xacro:property name="wheel_pose_r" value="0.0" />
  <xacro:property name="wheel_pose_p" value="0.0" />
  <xacro:property name="wheel_pose_y" value="0.0" />

  <xacro:macro name="wheel_unit_60mm" params="name parent xyz rpy">

  	  <!-- link to parent 
      <joint name="${parent}_${name}_joint" type="fixed">
	    <axis xyz="0 1 0"/>
	    <origin xyz="${xyz}" rpy="${rpy}" />
	    <parent link="${parent}"/>
	    <child link="${name}_wheel_base"/>
	  </joint>

	  <link name='${name}_wheel_base'>
	    <xacro:default_box  xyz=  "0 0 ${wheel_mount_axle_length/2 + wheel_base_size_z/2}" 
	                        rpy=  "0 0 0" 
	                        size= "${wheel_base_size_x} ${wheel_base_size_y} ${wheel_base_size_z}"/>  
	    <xacro:default_inertial mass="0.5"/>
	  </link>-->

	  <!-- joint between parent and wheel_mount_axle -->    
	  <joint name="${name}_caster" type="revolute">
	    <parent link="${parent}"/>
	    <child link="${name}_wheel_mount_axle"/>
	    <origin xyz="${xyz}" rpy="${rpy}"/>
	    <axis xyz="0 0 1" />
	    <dynamics damping="1.0" friction="0.0"/>  
	    <limit effort="10.0" lower="${-wheel_base_angle}" upper="${wheel_base_angle}" velocity="0.5"/>  
	  </joint>

	  <!-- Mount Axle --> 
	  <link name="${name}_wheel_mount_axle">   
	    <xacro:default_cylinder xyz=  "0 0 0 " 
	                            rpy=  "0 0 0" 
	                            radius="${wheel_mount_axle_radius}" 
	                            length="${wheel_mount_axle_length}"/>     
	    <xacro:default_inertial mass="0.5"/>
	  </link>

	  <!-- joint between wheel_mount_axle and wheel_mount_horplate -->    
	  <joint name="${name}_joint_wheel_mount_axle" type="fixed">
	    <parent link="${name}_wheel_mount_axle"/>
	    <child link="${name}_wheel_mount_horplate"/>
	    <axis xyz="0 1 0" />
	    <origin xyz="${-wheel_horplate_size_x/2 + wheel_mount_axle_radius + 0.01} 0 ${-wheel_mount_axle_length/2 - wheel_horplate_size_z/2}" rpy="0 0 0"/>    
	  </joint>

	  <!-- Horizontal plate -->
	  <link name="${name}_wheel_mount_horplate"> 
	    <xacro:default_box  xyz=  "0 0 0" 
	                        rpy=  "0 0 0" 
	                        size= "${wheel_horplate_size_x} ${wheel_horplate_size_y} ${wheel_horplate_size_z}"/>     
	    <xacro:default_inertial mass="0.5"/>    
	  </link>

	  <!-- joint between wheel_mount_horplate and wheel_mount_vertplate --> 
	  <joint name="${name}_joint_wheel_mount_vertplate" type="fixed">
	    <parent link="${name}_wheel_mount_horplate"/>
	    <child link="${name}_wheel_mount_vertplate"/>
	    <axis xyz="0 1 0" />
	    <origin xyz="${-wheel_horplate_size_x/2} 0 ${-wheel_vertplate_size_z/2}" rpy="0 0 0"/>    
	  </joint>

	  <!-- Vertical plate -->
	  <link name="${name}_wheel_mount_vertplate">     
	    <xacro:default_box  xyz=  "0 0 0" 
	                        rpy=  "0 0 0" 
	                        size= "${wheel_vertplate_size_x} ${wheel_vertplate_size_y} ${wheel_vertplate_size_z}"/>      
	    <xacro:default_inertial mass="0.5"/>
	  </link>

	  <!-- joint between wheel_mount_vertplate and wheel_axle --> 
	  <joint name="${name}_joint_wheel_axle" type="fixed">
	    <parent link="${name}_wheel_mount_vertplate"/>
	    <child link="${name}_wheel_axle"/>
	    <axis xyz="0 1 0" />
	    <origin xyz="${wheel_vertplate_size_x/2 + wheel_axle_length/2} 0 ${-wheel_vertplate_size_z/2 + wheel_axle_radius}" rpy="${wheel_axle_pose_r} ${wheel_axle_pose_p} ${wheel_axle_pose_y}"/>  
	  </joint>

	  <!-- Wheel Axle -->  
	  <link name="${name}_wheel_axle">   
	    <xacro:default_cylinder xyz=  "0 0 0" 
	                            rpy=  "0 0 0" 
	                            radius="${wheel_axle_radius}" 
	                            length="${wheel_axle_length}"/>         
	    <xacro:default_inertial mass="0.5"/>    
	  </link>

	  <!-- joint between wheel_axle and wheel -->    
	  <joint name="${name}_wheel" type="continuous">
	    <parent link="${name}_wheel_axle"/>
	    <child link="${name}_wheel"/>
	    <origin xyz="0 0 ${wheel_axle_length/2 + wheel_length/2} " rpy="0 0 0"/> <!-- axles are different -z y -x due to rotated -->
	    <axis xyz="0 0 1" />
	    <dynamics damping="10.0" friction="1.0" />      
	  </joint>  
	  
	  <!-- Wheel -->  
	  <link name="${name}_wheel">  
	    <xacro:default_inertial mass="0.5"/>
	    <collision>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
	        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
	      </geometry>  
	    </collision>
	    <visual>
	      <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
	        <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
	      </geometry>
	    </visual>
	  </link>

	  <gazebo reference="${name}_wheel">

	    <mu1>0.850000</mu1>
        <mu2>0.850000</mu2>
        <fdir1>1.000000 1.000000 0.000000</fdir1>

	  </gazebo>

	  <gazebo >
	    <plugin name="${name}_wheel_unit_controller" filename="libWheelUnitController.so">
	      <caster>${name}_caster</caster>
	      <wheel>${name}_wheel</wheel>  
	    </plugin>
	  </gazebo>
	</xacro:macro>
</robot>
